services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: estacionamento_db
      POSTGRES_USER: user_smartpark
      POSTGRES_PASSWORD: password_smartpark
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_smartpark -d estacionamento_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: