server:
  port: 8080

spring:
  application:
    name: dio-smartpark-api
  datasource:
    url: jdbc:postgresql://localhost:5433/estacionamento_db
    username: user_smartpark
    password: password_smartpark
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Para desenvolvimento. Em produção, prefira 'none' ou 'validate' com Flyway/Liquibase.
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  h2:
    console:
      enabled: false # Desabilitar H2 Console em produção

# Configurações do Flyway (se estiver usando)
# flyway:
#   enabled: true
#   locations: classpath:db/migration
#   baseline-on-migrate: true

# Configurações do Springdoc OpenAPI (Swagger UI)
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs